# Generated by Django 4.2.11 on 2025-01-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
        ('catalogue', '0029_default_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Travel Product', 'verbose_name_plural': 'Travel Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The end date and time of the travel', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates if the travel product has been approved by admin', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='The start date and time of the travel', null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
